version: '3'

services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "1935:1935"   # RTMP port
      - "8080:8080"   # HLS HTTP port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./hls:/var/www/hls
      - ./web:/var/www/html
    restart: always

  backend:
    image: node:20
    container_name: live-backend
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    ports:
      - "3000:3000"
    command: ["node","index.js"]
    restart: always
